name: my_rpg

on:
  push:
  pull_request:

env:
  EXECUTABLES: "my_rpg"

jobs:
  check_program_compilation:
    name: Check program compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Make
        run: make
      - name: Make clean
        run: make clean
      - name: Verify that all files are here
        run: |
            for FILE in $EXECUTABLES; do
              ./$FILE && echo "$FILE exists"
            done